apiVersion: cloudrun.gcp.upbound.io/v1beta1
kind: Service
metadata:
  annotations:
    meta.upbound.io/example-id: cloudrun/v1beta1/service
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    location: us-central1
    template:
    - spec:
      - containers:
        - image: gcr.io/cloudrun/hello
    traffic:
    - latestRevision: true
      percent: 100

---

apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: Subscription
metadata:
  annotations:
    meta.upbound.io/example-id: cloudrun/v1beta1/service
  labels:
    testing.upbound.io/example-name: subscription
  name: subscription
spec:
  forProvider:
    pushConfig:
    - attributes:
        x-goog-version: v1
      oidcToken:
      - serviceAccountEmail: ${google_service_account.sa.email}
      pushEndpoint: ${google_cloud_run_service.default.status[0].url}
    topicSelector:
      matchLabels:
        testing.upbound.io/example-name: topic

---

apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: Topic
metadata:
  annotations:
    meta.upbound.io/example-id: cloudrun/v1beta1/service
  labels:
    testing.upbound.io/example-name: topic
  name: topic
spec:
  forProvider: {}

---

apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: cloudrun/v1beta1/service
  labels:
    testing.upbound.io/example-name: sa
  name: sa
spec:
  forProvider:
    displayName: Cloud Run Pub/Sub Invoker

---

